### ISSUE TITLE
87 Minute “Just Ride” Average Output showing as 8 Minute

### ISSUE THREAD

**Issue by Metallirat** [jasonlutterloh/metrics-peloton#15]
When I uploaded my data I notice that I have 1 87 minute Just ride workout. It is showing as an 8 minute workout in the Average output section.

To Note: I did pull down the code and update it to pull 9999 rides and include same day rides, but that is the only modification I made.

**Comment by jasonlutterloh** [comment]
It seems there's a few issues with "just rides". I hadn't factored those in to the initial build. Ill take a look.

**Comment by jasonlutterloh** [comment]
As of [this commit](https://github.com/jasonlutterloh/metrics-peloton/commit/2e77d961572db204a8252c02e1dad80e0d2a025e), "Just Ride"s have been filtered out. I'm open to figuring out a way to incorporate them later but due to their inconsistency with the rest of the data (specifically the duration and titles that are accurate to the second as opposed to the minute), it makes more sense to remove them for the meantime.
