### ISSUE TITLE
4 minute and 45 minute ride average output showing NaN

### ISSUE THREAD

**Issue by Metallirat** [jasonlutterloh/metrics-peloton#16]
When I look at my average output data, the sections for 4 minute (I have two of them) and 45 minute Just rides are showing NaN. I have rides in the 40s (42 minute just ride for example) that is correctly showing average output.

To Note: I did pull down the code and update it to pull 9999 rides and include same day rides, but that is the only modification I made.

**Comment by jasonlutterloh** [comment]
Fixed this in [this commit](https://github.com/jasonlutterloh/metrics-peloton/commit/2e77d961572db204a8252c02e1dad80e0d2a025e). Error was due to output, distance, duration and a few other columns being empty in the CSV. Now by default, rows without the necessary data needed for the charts will be removed.
