### ISSUE TITLE
upload file but "view my metrics" does nothing

### ISSUE THREAD

**Issue by flare04** [jasonlutterloh/metrics-peloton#33]
either using the demo site or cloning the repo and running locally reacts in the same way.

I tried firefox and google chrome on Linux

**Comment by jasonlutterloh** [comment]
Hey @flare04 , is there anything that shows up in the console? Also, if you're comfortable with it, any chance you could email me the file you're trying to use? I'd like a chance to reproduce and see what's going on.

**Comment by flare04** [comment]
happy to share the file, there are only 10 rides in it, could that be the issue ?

**Comment by jasonlutterloh** [comment]
It shouldn't matter... but weirder things have happened. Can email me at peloton@lutterloh.dev. I'll try and take a look today

**Comment by flare04** [comment]
No errors in the browser console, and none on the cli.

**Comment by jasonlutterloh** [comment]
Good news, figured out the problem. Bad news is... it's going to take me a bit to fix. The distance in your CSV comes back with the title `Distance (km)` instead of `Distance (mi)` which I use by default. 
Sorry for the inconvenience but great find and thanks for sending that over! Haven't had a dataset where it came back like that but that makes sense. I don't think the fix should be too hard but I'll keep you posted.

**Comment by flare04** [comment]
OK glad I could be of help.  Oz uses Km, and the European countries.
Thanks for taking a look.

**Comment by jasonlutterloh** [comment]
Yeah, that was just short-sighted on my part. I built it off the datasets I had and Peloton doesn't publish any documentation or anything. Anyways, I pushed a fix. Should work now. Thanks again!

**Comment by flare04** [comment]
works great thanks
